int = ?/[-+]?[0-9]+/? ;
float = ?/[-+]?(\d+\.\d*)|(\d*\.\d+)/? ;
number = (float|int) ;
word = ?/[a-zA-Z_]+/? ;
name = ?/[a-zA-Z_][a-zA-Z0-9]*/? ;
metaName = ?/__[a-zA-Z][a-zA-Z0-9]*/? ;
commentText = ?/.*?(?=\*/|$)/? ;
defaultComment= "/*" comment:{commentText} "*/" ;
docComment = "/**" docComment:{commentText} "*/" ;
comment = (docComment|defaultComment) ;
manuallyReturn = (type:"ManuallyReturn" "<" value:int ">") ;
type = ( "int" | "float" | "double" | "string" | manuallyReturn ) ;
def = comment:{comment}type:type name:name "=" value:number ";";
arg = type:type name:name;
fDef = comment:{comment} return:(type|manuallyReturn|"void") name:name "(" [args:arg {"," args:arg}]  ")" ";" ;
mfDef = comment:{comment} return:(type|manuallyReturn|"void") name:metaName "(" [args:arg {"," args:arg}]  ")" ";" ;
class = "class" name:name ["extends" extends:name ]  "{" {fields:def|metaFunctions:mfDef|functions:fDef}* "}" $ ; 
