# $Id$
# This module defines:
# SQLITE3_LIBRARY_DIRS
# SQLITE3_INCLUDE_DIRS

FIND_PATH(SQLITE3_INCLUDE_DIRS sqlite3.h
	$ENV{CLIBS}/sqlite
)

IF(WIN32)
	SET(LIBSQLITE3 "sqlite3.lib")
ELSE(WIN32)
	SET(LIBSQLITE3 "libsqlite3.a")
ENDIF(WIN32)

FIND_PATH(SQLITE3_LIBRARY_DIRS ${LIBSQLITE3}
	$ENV{CLIBS}/sqlite
)

SET(SQLITE3_FOUND "NO")


IF(SQLITE3_LIBRARY_DIRS AND SQLITE3_INCLUDE_DIRS)
	SET(SQLITE3_FOUND "YES")
	message(STATUS "Detecting SQLITE3: SQLITE3 found.")
else(SQLITE3_LIBRARY_DIRS AND SQLITE3_INCLUDE_DIRS)
	if(SQLITE3X_FIND_REQUIRED)
      		message(SEND_ERROR "Unable to find the requested SQLITE3 libraries.")
	endif(SQLITE3X_FIND_REQUIRED)
ENDIF(SQLITE3_LIBRARY_DIRS AND SQLITE3_INCLUDE_DIRS)



