# $Id$
# This module defines:
# LIBZLIB_LIBRARY_DIRS
# LIBZLIB_INCLUDE_DIRS

FIND_PATH(LIBZLIB_INCLUDE_DIRS zlib.h
	$ENV{CLIBS}/zlib
)

IF(WIN32)
	SET(LIBZLIB "zlib.lib")
ELSE(WIN32)
	SET(LIBZLIB "zlib.a")
ENDIF(WIN32)

FIND_PATH(LIBZLIB_LIBRARY_DIRS ${LIBZLIB}
	$ENV{CLIBS}/zlib/lib
)

SET(LIBZLIB_FOUND "NO")


IF(LIBZLIB_LIBRARY_DIRS AND LIBZLIB_INCLUDE_DIRS)
	SET(LIBZLIB_FOUND "YES")
	message(STATUS "Detecting LIBZLIB: LIBZLIB found.")
else(LIBZLIB_LIBRARY_DIRS AND LIBZLIB_INCLUDE_DIRS)
	if(LIBZLIBX_FIND_REQUIRED)
      		message(SEND_ERROR "Unable to find the requested LIBZLIB libraries.")
	endif(LIBZLIBX_FIND_REQUIRED)
ENDIF(LIBZLIB_LIBRARY_DIRS AND LIBZLIB_INCLUDE_DIRS)



