# $Id$
# This module defines:
# LIBPIXMAN_LIBRARY_DIRS
# LIBPIXMAN_INCLUDE_DIRS

FIND_PATH(LIBPIXMAN_INCLUDE_DIRS pixman/pixman.h
	$ENV{CLIBS}/pixman/
)

IF(WIN32)
	SET(LIBPIXMAN "pixman-1.lib")
ELSE(WIN32)
	SET(LIBPIXMAN "libpixman.a")
ENDIF(WIN32)

FIND_PATH(LIBPIXMAN_LIBRARY_DIRS ${LIBPIXMAN}
	$ENV{CLIBS}/pixman/lib
)

SET(LIBPIXMAN_FOUND "NO")


IF(LIBPIXMAN_LIBRARY_DIRS AND LIBPIXMAN_INCLUDE_DIRS)
	SET(LIBPIXMAN_FOUND "YES")
	message(STATUS "Detecting LIBPIXMAN: LIBPIXMAN found.")
else(LIBPIXMAN_LIBRARY_DIRS AND LIBPIXMAN_INCLUDE_DIRS)
	if(LIBPIXMANX_FIND_REQUIRED)
      		message(SEND_ERROR "Unable to find the requested LIBPIXMAN libraries.")
	endif(LIBPIXMANX_FIND_REQUIRED)
ENDIF(LIBPIXMAN_LIBRARY_DIRS AND LIBPIXMAN_INCLUDE_DIRS)



