# $Id$
# This module defines:
# ICONV_LIBRARY_DIRS
# ICONV_INCLUDE_DIRS

FIND_PATH(ICONV_INCLUDE_DIRS iconv.h
	$ENV{CLIBS}/iconv/include
)

SET(LIBICONV libiconv.dylib)

FIND_PATH(ICONV_LIBRARY_DIRS ${LIBICONV}
	$ENV{CLIBS}/iconv/lib
)

SET(ICONV_FOUND "NO")


IF(ICONV_LIBRARY_DIRS AND ICONV_INCLUDE_DIRS)
	SET(ICONV_FOUND "YES")
	message(STATUS "Detecting ICONV: ICONV found.")
else(ICONV_LIBRARY_DIRS AND ICONV_INCLUDE_DIRS)
	if(ICONVX_FIND_REQUIRED)
      		message(SEND_ERROR "Unable to find the requested ICONV libraries.")
	endif(ICONVX_FIND_REQUIRED)
ENDIF(ICONV_LIBRARY_DIRS AND ICONV_INCLUDE_DIRS)



