# $Id$
# This module defines:
# LIBPNG_LIBRARY_DIRS
# LIBPNG_INCLUDE_DIRS

FIND_PATH(LIBPNG_INCLUDE_DIRS png.h
	$ENV{CLIBS}/libpng
)

IF(WIN32)
	SET(LIBPNG "libpng.lib")
ELSE(WIN32)
	SET(LIBPNG "libpng.a")
ENDIF(WIN32)

FIND_PATH(LIBPNG_LIBRARY_DIRS ${LIBPNG}
	$ENV{CLIBS}/libpng/lib
)

SET(LIBPNG_FOUND "NO")


IF(LIBPNG_LIBRARY_DIRS AND LIBPNG_INCLUDE_DIRS)
	SET(LIBPNG_FOUND "YES")
	message(STATUS "Detecting LIBPNG: LIBPNG found.")
else(LIBPNG_LIBRARY_DIRS AND LIBPNG_INCLUDE_DIRS)
	if(LIBPNGX_FIND_REQUIRED)
      		message(SEND_ERROR "Unable to find the requested LIBPNG libraries.")
	endif(LIBPNGX_FIND_REQUIRED)
ENDIF(LIBPNG_LIBRARY_DIRS AND LIBPNG_INCLUDE_DIRS)



