name: Windows Build

on:
  push:
    branches: 
        - master
        - feature/* 
        - bugfix/*
        - develop
        - bugfix/*
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init --recursive --remote
    - name: install dependencies
      run: choco install cygwin
    - name: build dependencies
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_arm64
        
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        sh build_CairoWin64.sh
      working-directory: scripts/clibBuilder
